language: c
env:
  global:
    - GAPROOT=gaproot

matrix:
  include:
    - env: CFLAGS="-O2"
      compiler: clang
    - env: CFLAGS="-O2"
      compiler: gcc
    - env: CFLAGS=""  # test build w/o optimization
    - env: ABI=32

before_script:
  - scripts/build_gap.sh
script:
  - scripts/run_tests.sh
